import { headers } from 'next/headers';
import { NextResponse } from 'next/server';
import { apiError } from '@/lib/api';
import { requireCapability } from '@/lib/authz';
import { ForbiddenError, UnauthenticatedError } from '@/lib/permissions';
import { clientIpFrom } from '@/lib/rate-limit';
import { unlinkStaffUser } from '@/lib/telegram/staff-linking';

/**
 * `POST /api/settings/users/:id/telegram` — revoke somebody's staff link.
 *
 * Revoke only, and that asymmetry is the design. Minting a link for another
 * user would produce a credential that has to travel to them somehow — email,
 * chat, read aloud — and each of those routes is worse than them pressing a
 * button on a screen they can already reach. `POST /api/profile/telegram`
 * has no id parameter at all for the same reason.
 *
 * What an administrator does need is the other half: a phone that has left
 * with somebody who has not come back. Deactivating the account does it too,
 * but a leaver is not always deactivated the same afternoon.
 */
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const query = new URLSearchParams();

  try {
    const user = await requireCapability('manageUsers');
    const audit = { userId: user.id, ip: clientIpFrom(await headers()) };
    const form = await request.formData();
    const intent = String(form.get('intent') ?? '');

    if (intent === 'unlink') {
      const result = await unlinkStaffUser(id, audit);
      if (!result.ok) query.set('telegramError', result.message);
    } else {
      // Including `link`. Minting for somebody else is not an oversight here
      // and should not read as one to whoever next opens this file.
      query.set('telegramError', 'A staff link can only be generated by its own user.');
    }
  } catch (error) {
    if (error instanceof UnauthenticatedError) {
      return apiError('UNAUTHENTICATED', 'Please sign in again');
    }
    if (error instanceof ForbiddenError) {
      return apiError('FORBIDDEN', error.message);
    }
    query.set(
      'telegramError',
      error instanceof Error ? error.message.slice(0, 300) : 'That could not be done',
    );
  }

  return new NextResponse(null, {
    status: 303,
    headers: { Location: `/settings/users/${id}?${query.toString()}` },
  });
}
